name: Calculate Scores

on:
  schedule:
    - cron: '*/2 * * * *'  # Cada 2 minutos
  workflow_dispatch:  # Permite ejecución manual

jobs:
  calculate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install gspread oauth2client pytz
        
    - name: Run calculator
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: |
        echo "$GOOGLE_CREDENTIALS" > encestadas.json
        python score_calculator.py
